# Generated by Django 4.2.27 on 2026-01-08 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=20, unique=True, verbose_name='Car Number')),
                ('car_model', models.CharField(max_length=100, verbose_name='Car Model')),
                ('seats', models.PositiveIntegerField(default=4, verbose_name='Number of Seats')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Year')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Color')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicle_photos/', verbose_name='Photo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='accounts.driverprofile', verbose_name='Driver')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['-created_at'],
            },
        ),
    ]
